### ISSUE TITLE
Page headline is too large when window is very wide

### ISSUE THREAD

**Issue by wslack** [18F/identity-intro#1]
Screenshots at varying widths:
<img width="600" alt="screen shot 2016-08-18 at 10 04 08 pm" src="https://cloud.githubusercontent.com/assets/10016577/17809761/cb3b08f8-65e6-11e6-805a-1d7d52f67f5c.png">
<img width="600" alt="screen shot 2016-08-19 at 8 26 09 am" src="https://cloud.githubusercontent.com/assets/10016577/17809752/c3e302cc-65e6-11e6-8732-c449e05e2054.png">
<img width="600" alt="screen shot 2016-08-19 at 8 26 29 am" src="https://cloud.githubusercontent.com/assets/10016577/17809756/c67ffed6-65e6-11e6-8f51-d1222036617f.png">

**Comment by brendansudol** [comment]
good catch, and thanks for the screenshots! this is fixed (https://github.com/18F/identity-intro/commit/37b37fdc092b15ae82bed0b11929668f8b837164)
